travis:
  secure:
    BINSTAR_TOKEN: dbN4WEczJwgZdxnZIZ3acryNBq4l0s3YmpxeCwSt/e7Xfjei+ExmV1OHUiW6R+M7NBRsF2fi8T5hdQLaL0IddJEz7nLuOAFHMadxMvgyVd/kRNYwQtroSQm90z32j+lN/1HTuxJz1fM9v9otgZFYs/PcpX6qxutyAcTWeZ2afVa0yPq94yktfF4BLVv9EvpSmwk1NKkOjYlA8GxbwSllc68QEhktNuDR0QMKpA79O1q6GV32/clom11lR2C7k8Q3rvzYxWvvmmR0XTGp1itAxHQyDBD1oMBhOuq8yu6hVkLk7NqjmknkHvbRel8juibDRJUiyGwsoH+GpI74qPIcQ8h85wR+qS9D/VJUUIijhEaboNdBAvRXZrT50bmOvNjeE2Xx4CfUUP7XVgeFI+uw5g8/MgTm4760pXRf84lx51EZVmTPI9YZ9r7Vd9FaKjPlmcV09dO3FAOdsMkPKzP4Vn/WpIHrh+Cxhf6lAkmYbO3glJ//ATXcdMaiogy1ZmmkcOfpLm7vcEJe4u4Om/zgmrqc8kHgMfptHsdjT1ARZl2QGFVny/idwoHd44jps8UdiHd6xAaTD7d2ahU9J6uJkCAneklIgVZa1Gx7tp3mUmZpHh8uaHRVqZokGU6dN2GTLbAYFmuuyeo0HsVkzaKXZNfJ1GZTYPXlAvDfHKpanoc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
